name: PMD Code Analysis

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  security-events: write

jobs:
  pmd-code-scan:
    name: PMD Code Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run PMD scan
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif